picasabuttonizer/urls.py
__author__ = 'fatrix'
from django.conf.urls.defaults import *

from xcore import urls
urlpatterns = patterns('',
    #url(r'^$', 'picasabuttonizer.views.index', name="buttonizer"),
    #url(r'^button/edit/(?P<guid>[0-9a-zA-Z-_]+)/$', 'picasabuttonizer.views.index', name="buttonizer_edit_button"),
    #url(r'^button/get/(?P<guid>[0-9a-zA-Z-_]+)/$', 'picasabuttonizer.views.get_button', name="buttonizer_get_button"),
    #url(r'^button/remove/(?P<guid>[0-9a-zA-Z-_]+)/$', 'picasabuttonizer.views.remove_button', name="buttonizer_remove_button"),
)
try:
    import mezzanine
except ImportError, e:
   urlpatterns += patterns('',
       url(r'^$', 'picasabuttonizer.views.index', name="buttonizer"),
   )

picasabuttonizer/models.py
from django.contrib.auth.models import User
from django.contrib.sessions.models import Session
from django.db import models
import uuid

class Button(models.Model):
    name = models.CharField(max_length=30, unique=True, verbose_name="name")
    user = models.ForeignKey(User, blank=True, null=True)
    guid = models.CharField(max_length=50, unique=True, null=True, blank=True)
    icon = models.FileField(upload_to="picasabuttonizer/icons")
    icon_name = models.CharField(max_length=30, null=True, blank=True)
    label = models.CharField(max_length=100)
    tooltip = models.CharField(max_length=100)

    #class Meta:
    #    abstract = True

    def save(self, force_insert=False, force_update=False, using=None):
        self.guid = str(uuid.uuid1())
        super(Button, self).save(force_insert, force_update, using)

    def delete(self, using=None):
        self.icon.delete()
        super(Button, self).delete(using)

    def id(self):
        return self.user.username+"/{"+self.guid+"}"

class HybridButton(Button):
    spec = models.URLField(verify_exists=False, max_length=30, verbose_name="URL of your Upload API")

class TrayexecButton(Button):
    spec = models.CharField(max_length=70, verbose_name="Path to command")

class OpenButton(Button):
    spec = models.CharField(max_length=70, verbose_name="Executable to open")

picasabuttonizer/forms.py
from django.forms.models import ModelForm
from django.forms import CharField
from django.forms.widgets import HiddenInput, TextInput
from models import Button
from picasabuttonizer.models import HybridButton, TrayexecButton, OpenButton

__author__ = 'fatrix'

class ButtonForm(ModelForm):
    guid = CharField(widget=HiddenInput(), required=False)
    id = CharField(widget=HiddenInput(), required=False)
    class Meta:
        model = Button
        exclude = ('user')

class HybridButtonForm(ModelForm):
    class Meta:
        model = HybridButton

class TrayexecButtonForm(ModelForm):
    class Meta:
        model = TrayexecButton

class OpenButtonForm(ModelForm):
    class Meta:
        model = OpenButton

picasabuttonizer/views.py
# Create your views here.
import django
from django.contrib import messages
from django.contrib.auth.models import AnonymousUser
from django.db.models.fields.files import FileField
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.shortcuts import render_to_response
from django.template.context import RequestContext
from buttonizer import Buttonizer
from picasabuttonizer.forms import HybridButtonForm, TrayexecButtonForm, OpenButtonForm
from picasabuttonizer.models import Button, HybridButton, TrayexecButton, OpenButton

def _model_form_type(type, model=None, form=None):
    if type == "hybrid":
        form = HybridButtonForm
        model = HybridButton
    if type == "exec":
        form = TrayexecButtonForm
        model = TrayexecButton
    if type == "open":
        form = OpenButtonForm
        model = OpenButton
    return form, model


def new_button(request, type):
    return {'form': _model_form_type(type)[0], 'type': type}


def index_handle(request, guid=None, type=None):
    print request.GET.items()

    form, model = _model_form_type(type)
    print form, model

    if request.method == 'POST':
        print "POST"
        try:
            instance = Button.objects.get(guid=guid)
            form = form(request.POST, request.FILES, instance=instance)
        except model.DoesNotExist:
            form = form(request.POST, request.FILES)
        if form.is_valid():
            button = form.save(commit=False)
            if not isinstance(request.user, AnonymousUser):
                # save button to db
                button.user = request.user
                button.save()
            else:
                button.save()
                session_buttons = request.session.get('buttons', [])
                session_buttons.append(button.guid)
                request.session['buttons'] = session_buttons
            messages.info(request, "Saved")
            print button
            return HttpResponseRedirect("/buttonizer/")
        else:
            print form.errors
    else:
        if type:
            if not guid:
                form = form()
            else:
                form = form(instance=Button.objects.get(guid=guid))
        else:
            # entry point
            return
    if request.user.is_authenticated():
        buttons = model.objects.filter(user=request.user.id)
    else:
        buttons = []
        for guid in request.session.get('buttons', []):
            try:
                buttons.append(model.objects.get(guid=guid))
            except model.DoesNotExist, e:
                pass

    return {'form': form, 'buttons': buttons}

def index(request, guid=None):
    vars = index_handle(request, guid)
    return render_to_response('pages/buttonizer.html', vars, RequestContext(request))


def remove_button(request, guid):
    button = Button.objects.get(guid=guid)
    button.delete()
    messages.info(request, "Deleted")
    if not request.user.is_authenticated():
        session_buttons = request.session.get('buttons')
        session_buttons.remove(guid)
    return index(request)


def _button_in_session(button_list, guid):
    return False

def _can_access(request, button, guid):
    if button.user:
        if button.user.id!=request.user.id:
            raise Button.DoesNotExist
    else:
        if _button_in_session(request.session.get('buttons', []), guid):
            raise Button.DoesNotExist

def get_button(request, guid):
    buttonizer = Buttonizer()
    try:
        button = Button.objects.get(guid=guid)
        _can_access(request, button, guid)
    except Button.DoesNotExist:
        raise Http404
    (name, button_file) = buttonizer.create_for_buttonmodel(button)
    response = HttpResponse(mimetype="appplication/zip")
    response['Content-Disposition'] = "attachment; filename="+name
    response.write(button_file.getvalue())
    button_file.close()
    return response

picasabuttonizer/templates/buttonizer_index.html
{% extends "base.html" %}

{% block title %}
    Picasa Buttonizer
{% endblock %}
{% block main %}
    <div class="grid_6">
        {% if not buttons %}
            <h2>You have not yet any button</h2>
            <p>Even you haven't an account on this site, you can
                create your buttons. They are accessible until the session
                expires.</p>
            <p>
                Registered users can create until 5 buttons.
            </p>
        {% else %}
            <h2>You have {{ buttons|length }} button{{ buttons|pluralize }}</h2>
            {% for button in buttons %}
                <p><h3>{{ button.name }}</h3>
                <a href="/buttonizer/button/edit/{{ button.guid }}">edit</a>
                <a href="/buttonizer/button/get/{{ button.guid }}">download</a>
                <a href="/buttonizer/button/remove/{{ button.guid }}">remove</a>
                </p>
            {% endfor %}

        {% endif %}
    </div>
    <div class="grid_10">
        <h2>Create new button</h2>

        <form action="/buttonizer/{{ edit_url }}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <p>
                {{ form.non_field_errors }}
            </p>

            <p>
                <label for="id_name">Name</label>
            </p>

            <p>{{ form.name.errors }}
                {{ form.name }}
            </p>

            <p><label for="id_icon">Icon</label></p>
            <p>
                {{ form.icon.errors }}
                {{ form.icon }}
            </p>
            <p>
                <label for="id_icon_name">Icon name</label>
            </p>
            <p>{{ form.icon_name.errors }}
                {{ form.icon_name }}
            </p>
            <p>
                {{ form.label.errors }}
                <label for="id_label">Label</label>
            </p>
            <p>
                {{ form.label }}</p>
            <p>
                <label for="id_tooltip">Tooltip</label>
            </p>
            <p>
                {{ form.tooltip.errors }}
                {{ form.tooltip }}
            </p>
            <p>
                <label for="id_hybrid_uploader_url">Hybrid uploader url</label></p>
            <p>
                {{ form.hybrid_uploader_url.errors }}
                {{ form.hybrid_uploader_url }}
            </p>
            <p>
                <br />
                <input type="submit" value="Submit"/>
            </p>
        </form>

        <p>
            {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message|safe }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        </p>
    </div>
{% endblock %}

picasabuttonizer/templates/pages/buttonizer.html
{% extends "base.html" %}
{% load i18n label_tags %}

{% block title %}
    <h2>{% trans "Picasa Buttonizer"|labelize:"class=title_first" %}</h2>
{% endblock %}

{% block extra_head %}
    <script type="text/javascript">
        $(function() {
            $("input:radio").click(radioClicked);
        });
        function radioClicked(e) {
           var type = e.currentTarget.value;
           $("#"+type).css('visibility', 'visible');
           var action = $("form#picasabuttonizer").attr("action");
            $("form#picasabuttonizer").attr("action", "/buttonizer/?edit=&type="+type+"/");
        }

    </script>
{% endblock %}



{% block main %}
    <div class="grid_6">
        {% if not buttons %}
            <h2>You have not yet any button</h2>
            <p>Even you haven't an account on this site, you can
                create your buttons. They are accessible until the session
                expires.</p>
            <p>
                Registered users can create until 5 buttons.
            </p>
        {% else %}
            <h2>You have {{ buttons|length }} button{{ buttons|pluralize }}</h2>
            {% for button in buttons %}
                <p>
                    <h3>{{ button.name }}</h3>
                    <a href="/buttonizer/?action=edit&guid={{ button.guid }}">edit</a>
                    <a href="/buttonizer/?get={{ button.guid }}">download</a>
                    <a href="/buttonizer/?remove={{ button.guid }}">remove</a>
                </p>
            {% endfor %}

        {% endif %}
    </div>
    <div class="grid_10">
        <h2>Create new button</h2>

        {# <form action="/buttonizer/{{ edit_url }}" method="POST" enctype="multipart/form-data"> #}
        <h3>Type {{ type }}</h3>
        {% if not form %}
        <form action="/buttonizer/?action=new&guid={{ guid }}&" method="GET">

            <input type="submit" name="type" value="hybrid">
            <input type="submit" name="type" value="exec">
            <input type="submit" name="type" value="open">
        </form>
        {% endif %}

        {% if form %}
    
        <form action="/buttonizer/?action=edit" method="POST" enctype="multipart/form-data" id="picasabuttonizer">
            {% csrf_token %}
            <p>
                {{ form.non_field_errors }}
            </p>

            <p>
                <label for="id_name">Name</label>
            </p>

            <p>{{ form.name.errors }}
                {{ form.name }}
            </p>

            <p><label for="id_icon">Icon</label></p>

            <p>
                {{ form.icon.errors }}
                {{ form.icon }}
            </p>

            <p>
                <label for="id_icon_name">Icon name</label>
            </p>

            <p>{{ form.icon_name.errors }}
                {{ form.icon_name }}
            </p>

            <p>
                {{ form.label.errors }}
                <label for="id_label">Label</label>
            </p>

            <p>
                {{ form.label }}
            </p>

            <p>
                <label for="id_tooltip">Tooltip</label>
            </p>

            <p>
                {{ form.tooltip.errors }}
                {{ form.tooltip }}
            </p>

            {{ form.spec.errors }}
            <p>
                <label>{{ form.spec.label }}</label>
            <p>
                {{ form.spec }}

            <p>
                <input type="hidden" name="type" value="{{ type }}"/>
                <input type="submit" value="Submit"/>
            </p>
        </form>

        {% endif %}

        <p>
            {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message|safe }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        </p>
    </div>
{% endblock %}